name: New Workflow
run-name: New Workflow

on: [push]

jobs:
  build:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4
      - name: Run one-line script
        run: echo "Hello, world"

  test:
    runs-on: ubuntu-laterst
    needs: build
    steps:
      - uses: actions/checkout@v4
      - name: Run some tests
<<<<<<< HEAD
        run: echo "Run some tests" 
=======
        run: echo "Run some tests"   
>>>>>>> 006b29cb5f266f8887314e4695dfc6e4060cf76f
