name: Publish image to docker hub
run-name: ${{ github.actor }} publish image to docker hub

on:
    push:
        branches:
            - main

jobs:
    build:
        runs-on: ubuntu-latest
        steps: 
            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v3

            - name: Login to docker hub
              uses: docker/login-action@v3
              with:
                 username: YevhenTrambai
                 password: ${{ secrets.DOCKER_SECRET }}

            - name: Build and push
              uses: docker/build-push-action@v5
              with:
                 push: true
                 tags: |
                  YevhenTrambai/web-sql:latest
                  YevhenTrambai/web-sql:${{ github.sha }}
